CREATE PROCEDURE [dbo].[FI_SP_IncBeneficiarioV2]
    @NOME          VARCHAR(50),
    @CPF           VARCHAR(11),
    @IDCLIENTE     BIGINT
AS
BEGIN

    INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
    VALUES (@NOME, @CPF, @IDCLIENTE);
    DECLARE @NewID BIGINT;
    SET @NewID = SCOPE_IDENTITY();

    SELECT NOME, CPF, IDCLIENTE, ID
    FROM BENEFICIARIOS
    WHERE ID = @NewID;
END