CREATE PROCEDURE [dbo].[FI_SP_ConsClientePorCPF]
    @CPF NVARCHAR(11)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, 
        LOGRADOURO, EMAIL, TELEFONE, ID, CPF 
    FROM CLIENTES WITH(NOLOCK)
    WHERE CPF = @CPF;
END